# for submitting mcnp runs
universe = vanilla
+SingularityImage="/software/kkiesling/dagmcnpww.sing"
requirements = HasSingularity && HasCHTCSoftware && (TARGET.HasChtcStaging == true) 
log = logs/dc_wwig_dagmcnp_$(Cluster)_dc$(s)_r$(r).log
error = logs/dc_wwig_dagmcnp_$(Cluster)_dc$(s)_r$(r).err
output = logs/dc_wwig_dagmcnp_$(Cluster)_dc$(s)_r$(r).out

# executable environment
environment = "DATAPATH=/staging/kkiesling/MCNP_DATA"
executable = run_wwig_dc.sh
arguments = $(r) $(s)

# input/output
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../performance-analysis/inputs/wwig.inp,../performance-analysis/wwigs/dc0.$(s)/r$(r),run_wwig.sh
#transfer_executable = False
transfer_output_files = outp,meshtal,ww_checks
# preserve_relative_paths = True
transfer_output_remaps = "outp=wwig_results/dc0.$(s)/r$(r)/outp ; meshtal=wwig_results/dc0.$(s)/r$(r)/meshtal ; ww_checks=wwig_results/dc0.$(s)/r$(r)/ww_checks"

# request resources
request_cpus = 1
request_memory = 5GB
request_disk = 3GB

# notify by email
notification = Always
notify_user = kkiesling@wisc.edu

# queue s, r from submit_list.txt
queue s, r from dc_redo_list.txt
