# for submitting mcnp runs
universe = vanilla
+SingularityImage="/software/kkiesling/dagmcnpww.sing"
requirements = HasSingularity && HasCHTCSoftware && (TARGET.HasChtcStaging == true) 
log = logs/reference_$(Cluster).log
error = logs/reference_$(Cluster)_$(Process).err
output = logs/reference_$(Cluster)_$(Process).out

# executable environment
environment = "DATAPATH=/staging/kkiesling/MCNP_DATA"
executable = run_analog.sh

# input/output
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../performance-analysis/inputs/analog.inp,run_analog.sh
#transfer_executable = False
transfer_output_files = outp,meshtal
# preserve_relative_paths = True
transfer_output_remaps = "outp=analog_results/outp ; meshtal=analog_results/meshtal"

# request resources
request_cpus = 1
request_memory = 5GB
request_disk = 2GB

# notify by email
notification = Always
notify_user = kkiesling@wisc.edu

queue 1
