# for submitting mcnp runs
universe = vanilla
+SingularityImage="/software/kkiesling/dagmcnpww.sing"
requirements = HasSingularity && HasCHTCSoftware && (TARGET.HasChtcStaging == true)
log = logs/wwig_deci_$(Cluster)_d$(r).log
error = logs/wwig_deci_$(Cluster)_d$(r).err
output = logs/wwig_deci_$(Cluster)_d$(r).out

# executable environment
environment = "DATAPATH=/staging/kkiesling/MCNP_DATA"
executable = run_wwig_refine.sh
arguments = $(r)

# input/output
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../../inputs/wwig_slab.inp,../../wwigs_slab/decimated/$(r),run_wwig_refine.sh
#transfer_executable = False
transfer_output_files = outp,meshtal,ww_checks
# preserve_relative_paths = True
transfer_output_remaps = "outp=wwig_deci/$(r)/outp ; meshtal=wwig_deci/$(r)/meshtal ; ww_checks=wwig_deci/$(r)/ww_checks"

# request resources
request_cpus = 1
request_memory = 1GB
request_disk = 500MB

# notify by email
notification = Always
notify_user = kkiesling@wisc.edu

queue r from 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
