# for submitting mcnp runs
universe = vanilla
+SingularityImage="/software/kkiesling/dagmcnpww.sing"
requirements = HasSingularity && HasCHTCSoftware && (TARGET.HasChtcStaging == true)
log = logs/wwig_ratio_$(Cluster)_r$(r).log
error = logs/wwig_ratio_$(Cluster)_r$(r).err
output = logs/wwig_ratio_$(Cluster)_r$(r).out

# executable environment
environment = "DATAPATH=/staging/kkiesling/MCNP_DATA"
executable = run_wwig.sh

# input/output
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../../inputs/wwig_slab.inp,../../wwigs_slab/r$(r)/geoms,run_wwig.sh
#transfer_executable = False
transfer_output_files = outp,meshtal,ww_checks
# preserve_relative_paths = True
transfer_output_remaps = "outp=wwig_ratio/r$(r)/outp ; meshtal=wwig_ratio/r$(r)/meshtal ; ww_checks=wwig_ratio/r$(r)/ww_checks"

# request resources
request_cpus = 1
request_memory = 2GB
request_disk = 500MB

# notify by email
notification = Always
notify_user = kkiesling@wisc.edu

queue r from seq 5 10 |
